# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  username: hoge
  password: hoge
  host: localhost
development:
  <<: *default
  database: blog_app_dev
  test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_pro